openapi: 3.0.0
x-stoplight:
  id: 8tlfrgw6uetjc
info:
  title: FROS
  version: '1.0'
  description: FROSのAPI仕様書
  contact:
    name: nothing
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userid}':
    get:
      summary: ユーザー情報取得
      tags:
        - users
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  info:
                    $ref: '#/components/schemas/user'
                  skills:
                    type: array
                    items:
                      $ref: '#/components/schemas/skill'
                  certifications:
                    type: array
                    items:
                      $ref: '#/components/schemas/certification'
                  priveleges:
                    type: array
                    items:
                      $ref: '#/components/schemas/privilege'
              examples: {}
        '204':
          description: No Content
        '400':
          description: Bad Request
      operationId: 'get-users-[userid]'
      description: ユーザー情報取得
      parameters: []
      x-internal: false
    put:
      summary: ユーザー情報編集
      operationId: 'put-users-[userid]'
      description: ユーザー情報編集
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                skills:
                  type: array
                  items:
                    $ref: '#/components/schemas/skill'
                certifications:
                  type: array
                  items:
                    $ref: '#/components/schemas/certification'
                privileges:
                  type: array
                  items:
                    $ref: '#/components/schemas/privilege'
                service_line:
                  type: string
            examples:
              Example 1:
                value:
                  skills:
                    - id: uuid
                      name: HTML
                      level: 2
                  certifications:
                    - id: uuid
                      name: AZ-104
                  authorities:
                    - id: uuid
                      name: githubの管理者
                  service_line: string
      tags:
        - users
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
    parameters:
      - schema:
          type: string
        name: userid
        in: path
        required: true
  /skills:
    get:
      summary: スキル一覧取得
      tags:
        - skills
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  skills:
                    type: array
                    description: 登録されているskillが配列で帰ってくる
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
              examples:
                Example 1:
                  value:
                    skills:
                      - id: uuid
                        name: HTML
                      - id: uuid
                        name: CSS
        '400':
          description: Bad Request
      operationId: get-skills
      description: スキル一覧取得
  /certifications:
    get:
      summary: 資格一覧取得
      tags:
        - certifications
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  certifications:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
              examples:
                Example 1:
                  value:
                    certifications:
                      - id: uuid
                        name: 応用情報
                      - id: uuid
                        name: AZ-104
        '400':
          description: Bad Request
      operationId: get-certifications
      description: 資格一覧取得
  /privileges:
    get:
      summary: 権限情報一覧取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  privileges:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
              examples:
                Example 1:
                  value:
                    authorities:
                      - id: uuid
                        name: github管理者
                      - id: uuid
                        name: azure管理者
        '400':
          description: Bad Request
      operationId: get-authorities
      description: 権限情報一覧取得
      tags:
        - privileges
    parameters: []
  /users:
    post:
      summary: ユーザー情報登録
      operationId: post-users
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
      tags:
        - users
      description: ユーザー情報登録
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
            examples: {}
        description: ''
  /search/skills:
    get:
      summary: スキルによるユーザー検索
      tags:
        - search
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        user:
                          type: object
                          properties:
                            id:
                              type: string
                              description: ユーザーid
                            name:
                              type: string
                              description: ユーザー名
                        skills:
                          type: array
                          description: userが持っているskill一覧の配列
                          items:
                            type: string
        '400':
          description: Bad Request
      operationId: get-search-skills
      description: スキル検索
      parameters:
        - schema:
            type: string
          in: query
          name: id
          description: スキルのuuid
  /search/certifications:
    get:
      summary: 資格によるユーザー検索
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        user:
                          type: object
                          properties:
                            id:
                              type: string
                              description: |
                                ユーザーid
                            name:
                              type: string
                              description: ユーザー名
                        certification:
                          type: object
                          properties:
                            name:
                              type: string
                              description: 資格名
                            expiration:
                              type: string
                              description: 資格の有効期限
        '400':
          description: Bad Request
      operationId: get-search-certifications
      description: 資格検索
      parameters:
        - schema:
            type: string
          in: query
          name: id
          description: 資格のuuid
      tags:
        - search
  /search/privileges:
    get:
      summary: 権限情報によるユーザ検索
      tags:
        - search
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        user:
                          type: object
                          properties:
                            id:
                              type: string
                              description: ユーザー名
                            name:
                              type: string
                              description: ユーザー名
                        privirage:
                          type: string
                          description: 権限情報名
        '400':
          description: Bad Request
      operationId: get-search-authorities
      description: 権限情報検索
      parameters:
        - schema:
            type: string
          in: query
          name: id
          description: 権限情報のuuid
    parameters: []
  /search/users:
    get:
      summary: ユーザー名によるユーザ検索
      tags:
        - search
      operationId: get-search-users
      description: ユーザー名検索のAPI
      parameters:
        - schema:
            type: string
          in: query
          name: name
          description: 検索内容（ユーザー名）
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        user:
                          type: object
                          description: 他のAPIと合わせるためにuserObjectの中に入れてます
                          properties:
                            id:
                              type: string
                              description: ユーザーid
                            name:
                              type: string
                              description: ユーザー名
        '400':
          description: Bad Request
components:
  schemas:
    skill:
      title: skill
      x-stoplight:
        id: i6jbotg7kmi6r
      type: object
      description: skill
      properties:
        id:
          type: string
          description: uuid
        name:
          type: string
          description: スキル名
        level:
          type: number
    certification:
      title: certification
      x-stoplight:
        id: h52jsyru8x4k2
      type: object
      properties:
        id:
          type: string
          description: uuid
        name:
          type: string
          description: 資格名
          example: AZ-104
    user:
      title: user
      x-stoplight:
        id: z6f6l8b36wynu
      type: object
      properties:
        id:
          type: string
          description: uuid
        name:
          type: string
        image:
          type: string
        email:
          type: string
        service_line:
          type: string
        isAdmin:
          type: boolean
    privilege:
      title: privilege
      x-stoplight:
        id: 6f2d6d266c7aa
      type: object
      properties:
        id:
          type: string
          description: uuid
        name:
          type: string
  responses: {}
security: []
tags:
  - name: certifications
  - name: privileges
  - name: search
  - name: skills
  - name: users
